export default ProductDummy = [
    {
      id: "1",
      name: "Nasi Goreng",
      category: "Makanan",
      price: 15000,
      rate: 4.5,
    },
    {
      id: "2",
      name: "Ayam Goreng",
      category: "Makanan",
      price: 20000,
      rate: 4.2,
    },
    {
      id: "3",
      name: "Es Teh Manis",
      category: "Minuman",
      price: 5000,
      rate: 4.0,
    },
    {
      id: "4",
      name: "Soto Ayam",
      category: "Makanan",
      price: 18000,
      rate: 4.6,
    },
    {
      id: "5",
      name: "Bakso",
      category: "Makanan",
      price: 12000,
      rate: 4.4,
    },
    {
      id: "6",
      name: "Sate Ayam",
      category: "Makanan",
      price: 15000,
      rate: 4.3,
    },
    {
      id: "7",
      name: "Jus Jeruk",
      category: "Minuman",
      price: 8000,
      rate: 4.7,
    },
    {
      id: "8",
      name: "Mie Goreng",
      category: "Makanan",
      price: 13000,
      rate: 4.1,
    },
    {
      id: "9",
      name: "Teh Hangat",
      category: "Minuman",
      price: 3000,
      rate: 4.2,
    },
    {
      id: "10",
      name: "Nasi Kuning",
      category: "Makanan",
      price: 17000,
      rate: 4.8,
    },
  ];